name: "Build Push Docker"

on:
  push:
    branches:
      - main
env:
  ECR_REGISTRY: ghcr.io
  ECR_REPOSITORY: ${{ github.repository }}

permissions:
  contents: write
  packages: write
  id-token: write
  # issues: write

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set IMAGE_TAG with timestamp
        run: |
          IMAGE_TAG="main-$(TZ=Asia/Bangkok date +%Y%m%d-%H%M)"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo and owner
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO=$REPO_LOWER" >> $GITHUB_ENV

      - name: Build and push the tagged docker image to Amazon ECR
        run: |
          docker buildx create --name multiarch-builder --driver docker-container --use
          docker buildx build --platform linux/amd64,linux/arm64  -t ${{ env.ECR_REGISTRY }}/$REPO:${{ env.IMAGE_TAG }}  --push .
          echo "IMAGE_URI=${{ env.ECR_REGISTRY }}/$REPO:${{  env.IMAGE_TAG }}" >> $GITHUB_ENV
